before_script:
  - virtualenv venv --quiet
  - source venv/bin/activate
  - pip install -r requirements.txt --quiet

pylint:
  script:
  - pip install pylint --quiet
  - pylint --rcfile=.pylintrc format.py
  - pylint --rcfile=.pylintrc parse.py
  - pylint --rcfile=.pylintrc maxskins
  - pylint --rcfile=.pylintrc tests/test_format.py
  - pylint --rcfile=.pylintrc tests/test_parse.py
  - pylint --rcfile=.pylintrc examples/PassThrough/client/py/Dynamic/PassThroughClient.py
  - pylint --rcfile=.pylintrc examples/PassThrough/client/py/BasicStatic/PassThroughClient.py
  - pylint --rcfile=.pylintrc examples/PassThrough/client/py/AdvancedStatic/PassThroughClient.py
  - pylint --rcfile=.pylintrc examples/Simple/client/py/Dynamic/SimpleClient.py
  - pylint --rcfile=.pylintrc examples/Simple/client/py/BasicStatic/SimpleClient.py
  - pylint --rcfile=.pylintrc examples/Simple/client/py/AdvancedStatic/SimpleClient.py

tests:
  script:
  - pip install nose
  - cd tests/
  - nosetests -v --with-coverage --cover-min-percentage=100
